# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uast_v2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uast_v2.proto',
  package='gopkg.in.bblfsh.sdk.v2.uast',
  syntax='proto3',
  serialized_pb=_b('\n\ruast_v2.proto\x12\x1bgopkg.in.bblfsh.sdk.v2.uast\"\x8b\x01\n\x04Node\x12\x0f\n\x05value\x18\x01 \x01(\x0cH\x00\x12\x35\n\x06object\x18\x02 \x01(\x0b\x32#.gopkg.in.bblfsh.sdk.v2.uast.ObjectH\x00\x12\x33\n\x05\x61rray\x18\x03 \x01(\x0b\x32\".gopkg.in.bblfsh.sdk.v2.uast.ArrayH\x00\x42\x06\n\x04node\"_\n\x05Value\x12\x0e\n\x04null\x18\x01 \x01(\x08H\x00\x12\r\n\x03str\x18\x02 \x01(\tH\x00\x12\r\n\x03int\x18\x03 \x01(\x03H\x00\x12\x0f\n\x05\x66loat\x18\x04 \x01(\x01H\x00\x12\x0e\n\x04\x62ool\x18\x05 \x01(\x08H\x00\x42\x07\n\x05value\"\x9b\x01\n\x06Object\x12?\n\x06\x66ields\x18\x01 \x03(\x0b\x32/.gopkg.in.bblfsh.sdk.v2.uast.Object.FieldsEntry\x1aP\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.gopkg.in.bblfsh.sdk.v2.uast.Node:\x02\x38\x01\"9\n\x05\x41rray\x12\x30\n\x05\x61rray\x18\x01 \x03(\x0b\x32!.gopkg.in.bblfsh.sdk.v2.uast.Nodeb\x06proto3')
)




_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='gopkg.in.bblfsh.sdk.v2.uast.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='gopkg.in.bblfsh.sdk.v2.uast.Node.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object', full_name='gopkg.in.bblfsh.sdk.v2.uast.Node.object', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='array', full_name='gopkg.in.bblfsh.sdk.v2.uast.Node.array', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='node', full_name='gopkg.in.bblfsh.sdk.v2.uast.Node.node',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=47,
  serialized_end=186,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='gopkg.in.bblfsh.sdk.v2.uast.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='null', full_name='gopkg.in.bblfsh.sdk.v2.uast.Value.null', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str', full_name='gopkg.in.bblfsh.sdk.v2.uast.Value.str', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int', full_name='gopkg.in.bblfsh.sdk.v2.uast.Value.int', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float', full_name='gopkg.in.bblfsh.sdk.v2.uast.Value.float', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool', full_name='gopkg.in.bblfsh.sdk.v2.uast.Value.bool', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='gopkg.in.bblfsh.sdk.v2.uast.Value.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=188,
  serialized_end=283,
)


_OBJECT_FIELDSENTRY = _descriptor.Descriptor(
  name='FieldsEntry',
  full_name='gopkg.in.bblfsh.sdk.v2.uast.Object.FieldsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='gopkg.in.bblfsh.sdk.v2.uast.Object.FieldsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='gopkg.in.bblfsh.sdk.v2.uast.Object.FieldsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=441,
)

_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='gopkg.in.bblfsh.sdk.v2.uast.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='gopkg.in.bblfsh.sdk.v2.uast.Object.fields', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_OBJECT_FIELDSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=441,
)


_ARRAY = _descriptor.Descriptor(
  name='Array',
  full_name='gopkg.in.bblfsh.sdk.v2.uast.Array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='array', full_name='gopkg.in.bblfsh.sdk.v2.uast.Array.array', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=500,
)

_NODE.fields_by_name['object'].message_type = _OBJECT
_NODE.fields_by_name['array'].message_type = _ARRAY
_NODE.oneofs_by_name['node'].fields.append(
  _NODE.fields_by_name['value'])
_NODE.fields_by_name['value'].containing_oneof = _NODE.oneofs_by_name['node']
_NODE.oneofs_by_name['node'].fields.append(
  _NODE.fields_by_name['object'])
_NODE.fields_by_name['object'].containing_oneof = _NODE.oneofs_by_name['node']
_NODE.oneofs_by_name['node'].fields.append(
  _NODE.fields_by_name['array'])
_NODE.fields_by_name['array'].containing_oneof = _NODE.oneofs_by_name['node']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['null'])
_VALUE.fields_by_name['null'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['str'])
_VALUE.fields_by_name['str'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['int'])
_VALUE.fields_by_name['int'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['float'])
_VALUE.fields_by_name['float'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['bool'])
_VALUE.fields_by_name['bool'].containing_oneof = _VALUE.oneofs_by_name['value']
_OBJECT_FIELDSENTRY.fields_by_name['value'].message_type = _NODE
_OBJECT_FIELDSENTRY.containing_type = _OBJECT
_OBJECT.fields_by_name['fields'].message_type = _OBJECT_FIELDSENTRY
_ARRAY.fields_by_name['array'].message_type = _NODE
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['Array'] = _ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
  DESCRIPTOR = _NODE,
  __module__ = 'uast_v2_pb2'
  # @@protoc_insertion_point(class_scope:gopkg.in.bblfsh.sdk.v2.uast.Node)
  ))
_sym_db.RegisterMessage(Node)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'uast_v2_pb2'
  # @@protoc_insertion_point(class_scope:gopkg.in.bblfsh.sdk.v2.uast.Value)
  ))
_sym_db.RegisterMessage(Value)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), dict(

  FieldsEntry = _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), dict(
    DESCRIPTOR = _OBJECT_FIELDSENTRY,
    __module__ = 'uast_v2_pb2'
    # @@protoc_insertion_point(class_scope:gopkg.in.bblfsh.sdk.v2.uast.Object.FieldsEntry)
    ))
  ,
  DESCRIPTOR = _OBJECT,
  __module__ = 'uast_v2_pb2'
  # @@protoc_insertion_point(class_scope:gopkg.in.bblfsh.sdk.v2.uast.Object)
  ))
_sym_db.RegisterMessage(Object)
_sym_db.RegisterMessage(Object.FieldsEntry)

Array = _reflection.GeneratedProtocolMessageType('Array', (_message.Message,), dict(
  DESCRIPTOR = _ARRAY,
  __module__ = 'uast_v2_pb2'
  # @@protoc_insertion_point(class_scope:gopkg.in.bblfsh.sdk.v2.uast.Array)
  ))
_sym_db.RegisterMessage(Array)


_OBJECT_FIELDSENTRY.has_options = True
_OBJECT_FIELDSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
