# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uast_v2_1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uast_v2_1.proto',
  package='gopkg.in.bblfsh.sdk.v2.uast.nodes',
  syntax='proto3',
  serialized_pb=_b('\n\x0fuast_v2_1.proto\x12!gopkg.in.bblfsh.sdk.v2.uast.nodes\"\xa3\x01\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\x04\x12;\n\x06object\x18\x02 \x01(\x0b\x32).gopkg.in.bblfsh.sdk.v2.uast.nodes.ObjectH\x00\x12\x39\n\x05\x61rray\x18\x03 \x01(\x0b\x32(.gopkg.in.bblfsh.sdk.v2.uast.nodes.ArrayH\x00\x12\x0f\n\x05value\x18\x04 \x01(\x0cH\x00\x42\x06\n\x04node\"{\n\x06Object\x12\x43\n\x05links\x18\x01 \x03(\x0b\x32\x34.gopkg.in.bblfsh.sdk.v2.uast.nodes.Object.LinksEntry\x1a,\n\nLinksEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\"\x16\n\x05\x41rray\x12\r\n\x05nodes\x18\x01 \x03(\x04\"p\n\x05Graph\x12\x36\n\x05nodes\x18\x01 \x03(\x0b\x32\'.gopkg.in.bblfsh.sdk.v2.uast.nodes.Node\x12\x0f\n\x07last_id\x18\x02 \x01(\x04\x12\x0c\n\x04root\x18\x03 \x01(\x04\x12\x10\n\x08metadata\x18\x04 \x01(\x04\"b\n\x05Value\x12\x10\n\x06string\x18\x01 \x01(\tH\x00\x12\r\n\x03int\x18\x02 \x01(\x03H\x00\x12\x0e\n\x04uint\x18\x03 \x01(\x04H\x00\x12\x0f\n\x05\x66loat\x18\x04 \x01(\x01H\x00\x12\x0e\n\x04\x62ool\x18\x05 \x01(\x08H\x00\x42\x07\n\x05valueb\x06proto3')
)




_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Node.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Node.object', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='array', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Node.array', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Node.value', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='node', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Node.node',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=55,
  serialized_end=218,
)


_OBJECT_LINKSENTRY = _descriptor.Descriptor(
  name='LinksEntry',
  full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Object.LinksEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Object.LinksEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Object.LinksEntry.value', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=343,
)

_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='links', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Object.links', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_OBJECT_LINKSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=343,
)


_ARRAY = _descriptor.Descriptor(
  name='Array',
  full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Array.nodes', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=367,
)


_GRAPH = _descriptor.Descriptor(
  name='Graph',
  full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Graph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Graph.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_id', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Graph.last_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='root', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Graph.root', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Graph.metadata', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=481,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Value.string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Value.int', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uint', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Value.uint', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Value.float', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Value.bool', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='gopkg.in.bblfsh.sdk.v2.uast.nodes.Value.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=483,
  serialized_end=581,
)

_NODE.fields_by_name['object'].message_type = _OBJECT
_NODE.fields_by_name['array'].message_type = _ARRAY
_NODE.oneofs_by_name['node'].fields.append(
  _NODE.fields_by_name['object'])
_NODE.fields_by_name['object'].containing_oneof = _NODE.oneofs_by_name['node']
_NODE.oneofs_by_name['node'].fields.append(
  _NODE.fields_by_name['array'])
_NODE.fields_by_name['array'].containing_oneof = _NODE.oneofs_by_name['node']
_NODE.oneofs_by_name['node'].fields.append(
  _NODE.fields_by_name['value'])
_NODE.fields_by_name['value'].containing_oneof = _NODE.oneofs_by_name['node']
_OBJECT_LINKSENTRY.containing_type = _OBJECT
_OBJECT.fields_by_name['links'].message_type = _OBJECT_LINKSENTRY
_GRAPH.fields_by_name['nodes'].message_type = _NODE
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['string'])
_VALUE.fields_by_name['string'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['int'])
_VALUE.fields_by_name['int'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['uint'])
_VALUE.fields_by_name['uint'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['float'])
_VALUE.fields_by_name['float'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['bool'])
_VALUE.fields_by_name['bool'].containing_oneof = _VALUE.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['Array'] = _ARRAY
DESCRIPTOR.message_types_by_name['Graph'] = _GRAPH
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
  DESCRIPTOR = _NODE,
  __module__ = 'uast_v2_1_pb2'
  # @@protoc_insertion_point(class_scope:gopkg.in.bblfsh.sdk.v2.uast.nodes.Node)
  ))
_sym_db.RegisterMessage(Node)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), dict(

  LinksEntry = _reflection.GeneratedProtocolMessageType('LinksEntry', (_message.Message,), dict(
    DESCRIPTOR = _OBJECT_LINKSENTRY,
    __module__ = 'uast_v2_1_pb2'
    # @@protoc_insertion_point(class_scope:gopkg.in.bblfsh.sdk.v2.uast.nodes.Object.LinksEntry)
    ))
  ,
  DESCRIPTOR = _OBJECT,
  __module__ = 'uast_v2_1_pb2'
  # @@protoc_insertion_point(class_scope:gopkg.in.bblfsh.sdk.v2.uast.nodes.Object)
  ))
_sym_db.RegisterMessage(Object)
_sym_db.RegisterMessage(Object.LinksEntry)

Array = _reflection.GeneratedProtocolMessageType('Array', (_message.Message,), dict(
  DESCRIPTOR = _ARRAY,
  __module__ = 'uast_v2_1_pb2'
  # @@protoc_insertion_point(class_scope:gopkg.in.bblfsh.sdk.v2.uast.nodes.Array)
  ))
_sym_db.RegisterMessage(Array)

Graph = _reflection.GeneratedProtocolMessageType('Graph', (_message.Message,), dict(
  DESCRIPTOR = _GRAPH,
  __module__ = 'uast_v2_1_pb2'
  # @@protoc_insertion_point(class_scope:gopkg.in.bblfsh.sdk.v2.uast.nodes.Graph)
  ))
_sym_db.RegisterMessage(Graph)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'uast_v2_1_pb2'
  # @@protoc_insertion_point(class_scope:gopkg.in.bblfsh.sdk.v2.uast.nodes.Value)
  ))
_sym_db.RegisterMessage(Value)


_OBJECT_LINKSENTRY.has_options = True
_OBJECT_LINKSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
